### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### Find an user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=test@gmail.com

### Delete an user with a given id
DELETE http://localhost:3000/auth/1

### Update an user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "changedPass"
}